### ISSUE TITLE
Removing defeated NPCs not working

### ISSUE THREAD

**Issue by rockwallguy** [veevelder/quick-combat#10]
Foundry 0.8.8, DnD5e 1.3.6, Windows 10 machine, self hosting foundry.

I've tried it in my usual world as well as a clean world with only Quick Combat active.  This is a new module for me, so user error could be an issue, but when I hit the hotkey to start combat, everything works properly.  I mark some NPCs defeated, then hit the hotkey again.  The dialogue box pops up, I click yes, and combat ends.  The music goes back to normal like it should and xp for the defeated enemies are calculated, but the defeated NPC tokens are not being removed.

"Remove Defeated NPCs?" check box is active.

**Comment by veevelder** [comment]
thanks for the catch, fixed in the new release.
