### ISSUE TITLE
[Request] Combat Playlist Toggle/Hotkey

### ISSUE THREAD

**Issue by Lyra214** [veevelder/quick-combat#11]
It would be highly practical if there could be either a quick toggle, or perhaps even better, an additional hotkey (configurable, such as CTRL+ALT+C) to start combat _without_ the combat playlist. I often find myself wanting to start a combat without the standard battle music, or more elaborate sounds, and I'd love to have the options to quickly start combat without the playlist in some cases, with it in others.

**Comment by veevelder** [comment]
thanks for the suggestion, I added it to the newest version.
