### ISSUE TITLE
An error appears when creating or deleting a combat

### ISSUE THREAD

**Issue by Milkhare** [veevelder/quick-combat#12]
Hey! When I create or delete a combat, an error message appears in the players console. Could this somehow affect the game and can it somehow be fixed? I'm sorry, English is not my first language.
![2021-07-15 20_50_46-DevTools - 26 200 120 132_30000_game](https://user-images.githubusercontent.com/82135041/125818203-b421aba6-fd1a-4227-96ab-2cf5f9f8d8e1.png)
![2021-07-15 20_51_10-DevTools - 26 200 120 132_30000_game](https://user-images.githubusercontent.com/82135041/125818206-4ab2fe94-7147-4d08-8d56-0f0e1d1cb6a7.png)

**Comment by veevelder** [comment]
It shouldn't cause any issues with the player, however I did figure out what was going on and fixed in the newest release.
