### ISSUE TITLE
Combat music fadeout

### ISSUE THREAD

**Issue by solashira** [veevelder/quick-combat#13]
This is more of a suggestion than a issue, sorry for putting it the wrong place.
It would be reeeeeally nice if you could integrate a function which plays a playlist after combat ends, that should enable DMs to add a combat fadeout tune instead of the music ending abruptly.

**Comment by veevelder** [comment]
Thats a good idea, I was thinking of adding a fanfare playlist option that will play a combat fanfare track at the end of combat, so that should do the same thing for you.

**Comment by veevelder** [comment]
I added something in the newest release, its the Fanfare playlist. Let me know if that is what you where thinking of.

**Comment by solashira** [comment]
> I added something in the newest release, its the Fanfare playlist. Let me know if that is what you where thinking of.

Thank you so much! You've just brought immersive DMing to the next level!
