### ISSUE TITLE
[Feature Request] Add Support for playing 'Boss Playlist' instead of 'Combat Playlist'

### ISSUE THREAD

**Issue by MarkeyMarke** [veevelder/quick-combat#14]
I like to give boss encounters a second different playlist, so it would be great if there's a way to configure this module to automatically play the boss playlist for special encounters!

Perhaps we could add another option where, by using a different hotkey combination, I could start an encounter using the boss playlist?

**Comment by veevelder** [comment]
thats something I could add, I will get right on it

**Comment by veevelder** [comment]
added in the newest release
