### ISSUE TITLE
Combat Playlist doesn't start in combat, throws console error

### ISSUE THREAD

**Issue by JasonSlingsCode** [veevelder/quick-combat#15]
Steps to reproduce:
1.) Set a combat playlist in module settings
2.) Start a combat in a scene using the tracker
3.) The playlist doesn't commence.

The browser console shows an error such as this: 
![image](https://user-images.githubusercontent.com/5216225/146684950-a717a678-e7c2-4278-b7de-6c84463b3351.png)

**Comment by veevelder** [comment]
which version of foundry and quick hits are you running?

**Comment by JasonSlingsCode** [comment]
Foundry: 8.9
QC: 0.2.5

Sorry for the delay. Holidays and all. The other day I tried rolling back to the previous version of QC which I got from this GitHub and got the same console error. I'm back on 0.2.5.

Let me know if you need any additional info

**Comment by veevelder** [comment]
thanks sorry for taking so long to get back to you. Can you turn on the debug output on the console for me so I can see the output? Also I think I know the reason, if you could try and resave the quick combat settings I changed how the playlists are saved and im wondering if thats the cause.

**Comment by veevelder** [comment]
I managed to recreate the issue, and it was what I suspected, I will make a note of it on the readme let me know if the fix works for you.

**Comment by JasonSlingsCode** [comment]
Hi there, there looks like an issue pulling 0.2.6, can you check?

**Comment by veevelder** [comment]
It seems to work for me, 0.2.6 is for FoundryVTT version 9

**Comment by JasonSlingsCode** [comment]
Seems to be working for me now.

I installed 0.2.6 and tested the playlist playing using the Begin/End Combat button. The Combat playlist doesn't play - here is the error:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'playAll')
[Detected 1 package: quick-combat]
    at quick-combat.js:231
    at Function._call (foundry.js:294)
    at Function.call (foundry.js:279)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:10126)
    at async ClientDatabaseBackend._updateDocuments (foundry.js:10027)
    at async Function.updateDocuments (document.mjs:373)
    at async Combat.update (document.mjs:456)
    at async CombatTracker._onCombatControl (foundry.js:58273)

**Comment by JasonSlingsCode** [comment]
Testing further, it seems to work correctly when I begin combat using the hotkey method. I'm able to begin and end combat that way and the playlist plays everything correctly. It's only when using the Begin/End Combat button using the sidebar tracker where the error is thrown.

**Comment by veevelder** [comment]
ohhhh, I see I can take a look at that.

**Comment by veevelder** [comment]
ok, I think I fixed your issue can you install the latest version and let me know?

**Comment by JasonSlingsCode** [comment]
Using 0.2.7 now - I followed the same steps and nothing happened with the playlist on the "start combat" action using the tracker button. There was also no console error this time.

However, when I clicked the button again to *end* combat, it asked me if I wanted to start the combat playlist.

**Comment by veevelder** [comment]
can you get console logs and screen captures of this happening?

**Comment by JasonSlingsCode** [comment]
I cleared the console and hit the "Begin Combat" button. Next post will have the "End Combat" stuff. 

Here are the logs:

Console was cleared
undefined
foundry.js:3022 Foundry VTT | Rendering Dialog
monks-tokenbar.js:25 monks-tokenbar |  Changing global movement combat
foundry.js:3022 Foundry VTT | Rendering Tidy5eSheet
2foundry.js:5069 game.data.version is deprecated since V9 in favor of game.version
get @ foundry.js:5069
(anonymous) @ hooks.js:307
_call @ foundry.js:294
call @ foundry.js:279
_render @ foundry.js:3086
await in _render (async)
_render @ foundry.js:3733
render @ foundry.js:2990
render @ foundry.js:4228
cycleSheets @ nextUp.js:413
handleCombatUpdate @ nextUp.js:348
_call @ foundry.js:294
callAll @ foundry.js:253
callback @ foundry.js:10216
(anonymous) @ foundry.js:10155
_handleUpdateDocuments @ foundry.js:10155
_updateDocuments @ foundry.js:10036
await in _updateDocuments (async)
update @ backend.mjs:154
await in update (async)
updateDocuments @ document.mjs:373
update @ document.mjs:456
startCombat @ foundry.js:15700
_onCombatControl @ foundry.js:58273
(anonymous) @ foundry.js:58195
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
monks-tokenbar.js:25 monks-tokenbar |  display notification

Here's the screenshot.
<img width="1433" alt="Screen Shot 2022-01-06 at 12 12 53" src="https://user-images.githubusercontent.com/5216225/148422717-c090af91-0589-471a-bc8b-8b20fa514c25.png">

**Comment by JasonSlingsCode** [comment]
Here I cleared the console again and used the "End Combat" button.

Logs:

Console was cleared
undefined
foundry.js:3022 Foundry VTT | Rendering Dialog
foundry.js:3022 Foundry VTT | Rendering AssignXPApp
backend.mjs:306 Foundry VTT | Deleted Combat with id [vyv6vyKf0mRFJO9v]
foundry.js:3022 Foundry VTT | Rendering LootablesApp
foundry.js:3022 Foundry VTT | Rendering Dialog3
monks-tokenbar.js:25 monks-tokenbar |  Changing global movement free
monks-tokenbar.js:25 monks-tokenbar |  display notification

Screenshot:
<img width="1408" alt="Screen Shot 2022-01-06 at 12 17 32" src="https://user-images.githubusercontent.com/5216225/148423399-6af61441-5df6-41a7-a02d-1a81220a7d34.png">

**Comment by veevelder** [comment]
can you get the output of the console again with the debug level turned on? It needs to be set under the Default levels drop down.

**Comment by veevelder** [comment]
also can you take a screen shot you your quick combat settings, thanks

**Comment by veevelder** [comment]
also also, can I get a list of other mods you are using? I want to see if theres a possible conflict going on there. You can also try to see if thats the case by disabling some mods to see if quick combat works.

**Comment by JasonSlingsCode** [comment]
Hm, I'm not sure what changed, but it seems to work correctly on combat start and I see no console errors. i.e. When I press the `Begin Combat` button I get a dialog asking if I want to start the combat playlist or not. So this aspect seems resolved. Thanks!

However, I did notice that if I have the scene activated, and a playlist is playing, I can `Begin Combat` and select to *not* play the combat playlist. The original playlist continues to play. But when I `End Combat`, it will stop the first playlist, which had been playing since before combat. (in other words, I get silence since no playlist is playing)

Note that if I choose to play the combat list on `Begin Combat`, it does play the combat playlist in combat, then continues playing the first playlist when I `End Combat`. This behavior is as I expected.

Is there a way to have it simply play the combat playlist, and going back to the original playlist, without giving a dialog choice?

**Comment by veevelder** [comment]
I'm glad everything is working again, and yeah, I can look into adding an option to just ignore the dialog

**Comment by JasonSlingsCode** [comment]
Well it's mostly working, sufficient for me, thanks for your hard work! The only issue I notice as mentioned above is selecting "do not play combat playlist" will cause your original playlist to stop playing when combat ends (i.e. you get silence).

**Comment by veevelder** [comment]
so I think I fixed that issue, I also added an option to not display the playlist choose dialog so as long as you have a combat playlist set it should just start

**Comment by JasonSlingsCode** [comment]
Thanks! Works great!

**Comment by veevelder** [comment]
Your welcome, thanks for your help in debugging I appreciate it.
