### ISSUE TITLE
Feature Request: OSE Support

### ISSUE THREAD

**Issue by justinthejaguar** [veevelder/quick-combat#17]
Is there any way you could add support for Old-School Essentials? https://github.com/vttred/ose

Currently toggling the combat will freeze combat in an infinite loop for group initiative.

**Comment by veevelder** [comment]
I can look into it.

**Comment by veevelder** [comment]
So I added support for OSE, and I think I have the experience tracking stuff implemented correctly. Im not 100% sure since I have never played or used this system before. Please let me know if anything is wrong with it.

**Comment by justinthejaguar** [comment]
It doesn't seem to be whispering XP after combat currently. One thing that I would request is not auto-rolling the initiative. In this system group combat is used by default, so the player needs to flag enemies, and before initiative is rolled each round, players need to state whether they are retreating or casting a spell.

**Comment by veevelder** [comment]
Thanks for the info, yeah I wasnt sure about the rolling initiatives part of it, I set it up to use the system to roll for initiative, but I can remove it. I can also check on the whisper XP part of it as well.

**Comment by veevelder** [comment]
sorry for the late fix, but I removed the initiative stuff and I checked on the whisper XP and it seems to be working just fine. Can you provide the debug console log and screen shots of it not working so I can figure out what is going on?

**Comment by veevelder** [comment]
@justinthejaguar did you have a chance to checkout the latest version?

**Comment by justinthejaguar** [comment]
I did indeed. It went smoothly in my Saturday game. Thank you. The only weird thing I had happen was at the end of one of the combats the music kept playing after ending the encounter. I can't replicate it now though. Maybe I did something wrong.

**Comment by veevelder** [comment]
strange, I will keep an eye out for it as well, if you ever do come across it again make another issue. Thanks for your help!
