### ISSUE TITLE
Suggestion: Put "dnd5e" in the `title` of this module

### ISSUE THREAD

**Issue by akrigline** [veevelder/quick-combat#2]
I'm not certain that this is only for dnd5e, but I assume so, and that's actually kind of my point.

It's not immediately apparent that this is only for dnd5e on the package list (or readme), and doing this would help GMs who don't use dnd5e immensely.

**Comment by veevelder** [comment]
The intention of this is to be able to use it for any system, but I haven't had the time to check/test yet. But I can add some details saying as such.
