### ISSUE TITLE
[FEATURE] add aditional custom playlists to start when combat starts

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [veevelder/quick-combat#20]
**Is your feature request related to a problem? Please describe.**
i would like to add another catergory of music to play when combat starts. for mini bosses. as thats common in pf2. 

**Describe the solution you'd like**
another play list to pull from called mini bosses or ultimatley being able to increase/ decrease your own custom play lists to add for when combat starts.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by veevelder** [comment]
Just to clarify you want an additional playlist other than the boss playing listed here https://github.com/veevelder/quick-combat#settings?

So you want a normal combat playlist, mini boss playlist and a boss playlist?

**Comment by ThingsCouldGetDicey** [comment]
> Just to clarify you want an additional playlist other than the boss playing listed here https://github.com/veevelder/quick-combat#settings?
> 
> So you want a normal combat playlist, mini boss playlist and a boss playlist?

correct. and or abilities to set as many as you want but having the mini boss playlist would suit 90% of purposes.

**Comment by veevelder** [comment]
👍

**Comment by ThingsCouldGetDicey** [comment]
also optimisation for pf2e would be much much appreciated too. as thats where im using it. the auto playlists are so useful to me. thank you ver much for your work!

**Comment by veevelder** [comment]
ok so I added the new playlist feature in the newest release, check it out and let me know if that works for you, and what kind of pf2e optimizations are you thinking of? (other than your other issue)

**Comment by ThingsCouldGetDicey** [comment]
thank you for doing this! much appreciated!

**Comment by ThingsCouldGetDicey** [comment]
when you update you get repeated alerts for the settings that constantly spam. it should be limited to one time.

**Comment by ThingsCouldGetDicey** [comment]
![image](https://user-images.githubusercontent.com/62528192/205433241-d5f8e50f-d883-4ddc-99fb-5681fccaaec5.png)
its every time i log in

**Comment by veevelder** [comment]
ok, I reworked how the migration stuff is done, and hopefully it shouldn't spam you anymore

**Comment by ThingsCouldGetDicey** [comment]
> ok, I reworked how the migration stuff is done, and hopefully it shouldn't spam you anymore

thank you for being so quick on this. you do great work. if you want to troubleshoot with the loading previous playlist issue my discord is GuitarGuyNick#7895

**Comment by ThingsCouldGetDicey** [comment]
one thing i did want to mention about the new options is the fanfare has a check mark but no way to set the fanfare music? or maybe i misunderstand how to set that up. its not clear.

**Comment by veevelder** [comment]
I should have fixed the spamming message issue, can you update and see if it has been fixed for you
