### ISSUE TITLE
[ISSUE] Initiative auto roll npcs doesnt work on pf2 correctly

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [veevelder/quick-combat#21]
**Describe the bug**
pf2 has an auto roll of npcs hook by shift clicking the npcs in the combat tracker. currently when using the feature to auto roll npcs in the system will pull up roll dialogues for each npc forcing the user to click all of the manually.

**To Reproduce**
1. enable npc auto roll within a pf2 system game
2. have alot of npcs
3. start combat 
4. See all of the dialogue rolls.

**Expected behavior**
what i expect to replace the current behaviour is just to auto roll the intiative without the dialogue with the assumed perception skill. 

**Screenshots**

**Version Information**
 - Quick Combat: Current
 - FoundryVTT: Current
 - System:PF2e
 - Other Modules:

**Additional context**

**Comment by veevelder** [comment]
ive added a new setting for quick combat (https://github.com/veevelder/quick-combat#pathfinder-second-edition---skip-dialog) that should take care of what you want. Let me know if there is anything else you would like to add for PF2e

**Comment by ThingsCouldGetDicey** [comment]
i mean if you can do it we are looking for a solution to being able to select the kind of intiative before combat starts. so a selection box of the skill checks for intiative would be amazing.

**Comment by ThingsCouldGetDicey** [comment]
https://github.com/foundryvtt/pf2e/issues/4267

**Comment by veevelder** [comment]
I can look into it, but I just want to clarify a few things as im not to familiar with PF2e.

Is the type of initiative the same for all PCs/NPCs, or can they be different?
Is this something a player should determine or just the GM?

If I cant find a "simple" solution I can monitor the issue you linked to see if they make any updates and adjust my stuff as needed.

**Comment by ThingsCouldGetDicey** [comment]
> I can look into it, but I just want to clarify a few things as im not to familiar with PF2e.
> 
> Is the type of initiative the same for all PCs/NPCs, or can they be different? Is this something a player should determine or just the GM?
> 
> If I cant find a "simple" solution I can monitor the issue you linked to see if they make any updates and adjust my stuff as needed.

the gm detemines the roll. based on what the pcs or npcs where doing prior to the call for intiative.  the default is perception based checks. as thats the most common the second common is stealth rolls. the idea being that if they roll higher with stealth they get to go first in initiative. there are no surprise rounds.  but for example if a pc wanted to bluff his way to get closer to an npc the intiative roll would be deception instead of the usual perception skill. this also could be different per pc and per npc. depending on what they were doing prior. but the most common is perception and stealth. 

which is why if you can do something to contribute to the system that did add the intaitive selection on the roll dialogue or something that could ask the gm "hey do you wanna roll X skill for all npcs" that would be a good solution for the most part.

**Comment by veevelder** [comment]
Ok, so I think I may have a solution to this, I haven't pushed into the code base yet but here is what it will look like.

New setting to Group NPC rolls by initiative type

![group_npc_setting](https://user-images.githubusercontent.com/5912400/208531211-42823d9a-80cf-42a2-84b1-ed354d889eb2.png)


When enabled it will pop up a new window to select which skill to roll with

![group_npc_dialog](https://user-images.githubusercontent.com/5912400/208531305-858cd9e2-411e-4a59-b4a4-5c0fc9c24f03.png)

This will enable all NPCs to use that skill to roll for initiative  but still ask for the PCs (the window will still pop up).

![group_npc_roll_result](https://user-images.githubusercontent.com/5912400/208531614-70af2a23-ac78-4860-be3a-363a2b4fd459.png)
(the 1 actor is the PC)

Obviously with this option disabled it will still popup the windows for every combatant. After you've selected the skill to roll with normal quick-combat stuff will happen. So does this work for your needs or do you have something else in mind?

**Comment by ThingsCouldGetDicey** [comment]
usually it will be either perception as default or stealth for npcs. for players its more vital to have the selection. for that pop up. it will be much rarer for npcs to need other checks. but for players its more frequent. if they could click the intiative roll button on the combat tracker and for that drop down menu to happen for them that would be very useful to players.

**Comment by veevelder** [comment]
Ok, how does this look then? (GM on left player on right)

![group_npc_setting](https://user-images.githubusercontent.com/5912400/208732195-226015d8-a797-49b6-a83f-98afedb3205f.png)


The GM initiates combat a pop up will display for him asking for the type
![group_roll_gm](https://user-images.githubusercontent.com/5912400/208732279-75430634-adc3-44d4-a50d-9a0f13e55d8e.png)

It will then ask the players for the type
![group_roll_player](https://user-images.githubusercontent.com/5912400/208732321-7c9ba596-5d83-4c5e-a173-d41aac0db346.png)

and once all players have submitted it will roll and start combat
![group_npc_roll_result](https://user-images.githubusercontent.com/5912400/208732395-f24cf857-8de8-41d1-a13b-3648962e3f6f.png)

**Comment by ThingsCouldGetDicey** [comment]
this looks amazing. have you shared this with the pf2 devs?

**Comment by ThingsCouldGetDicey** [comment]
could you post a gif of this working so i could see it in action?

**Comment by veevelder** [comment]
Here is a gif of it working, sorry for the terrible quality.

https://media.giphy.com/media/le4xPKGehEvwLorWb2/giphy.gif

**Comment by ThingsCouldGetDicey** [comment]
cool i would have an option to enable gms to individually select each npc for a box selection too and with a short cut to bypass group selection when grouping them just incase.  as this may come up in the future.  then i think its sorted.

**Comment by veevelder** [comment]
ok how does this look then? New Settings Option to choose from

![group_npc_setting](https://user-images.githubusercontent.com/5912400/209000306-5516edfa-5967-4869-b361-7be8871eca92.png)

Default - system default it will prompt for every combatant
![pf2e_default](https://user-images.githubusercontent.com/5912400/209000394-ebfc301c-c812-4c00-8c51-538ed1dbc538.png)

Fast - will assume Perception for every combatant, and wont prompt
![pf2e_fast](https://user-images.githubusercontent.com/5912400/209000405-82ed954e-7732-4130-9eb2-2ae07f063ba7.png)

Prompt - will prompt GM and Players to pick which initiative type to roll with
* GM will have an NPC prompt to either Group NPCs types OR pick individual initiative type
![pf2e_gm_prmopt](https://user-images.githubusercontent.com/5912400/209000428-9bb6c111-527c-47da-be8e-eedd983aec91.png)
![pf2e_player_prmopt](https://user-images.githubusercontent.com/5912400/209000437-68170aca-39e6-4b54-afe7-a0477c1c2e98.png)

**Comment by ThingsCouldGetDicey** [comment]
that is amazing! better than i expected. maybe one more option fast for gm (i.e always rolling perception) prompt for players? but what youve done for prompt is how id use it. 

so the way i understand it you get the prompt at the top to group npcs to whatever that box is but if you wanted to individualise it you could by unselecting it and doing it manually right?

**Comment by veevelder** [comment]
I can add that option.

and yeah, if you have that checkbox selected it will roll whatever you have selected in the drop down for every NPC.

however if you uncheck that checkbox, for each NPC listed below it will roll whatever you have in their drop downs

**Comment by ThingsCouldGetDicey** [comment]
also intaitive rolls shouldnt default to blind. they should be public rolls.  just to be clear.

**Comment by ThingsCouldGetDicey** [comment]
there maybe an instance where the gm may want to roll in secret. so you could put in a clause when the gm rolls stealth for inatiative. its a non public roll.  not even blind because the gm wouldnt want the players to see the dice. then all bases are covered.

**Comment by veevelder** [comment]
I don't think the pf2e system will let me set the chat output options, but if the GM sets the roll type before rolling it will be set for all the rolls, so they can use it to set public/private rolls in that case. I can set things as secret but that doesn't appear to be the same thing.

without secret public rolls
![public_rolls](https://user-images.githubusercontent.com/5912400/209007527-7aaa148c-6caf-49e1-8e96-86b4fdb8b5de.png)

with secret rolls public rolls
![public_rolls_secret](https://user-images.githubusercontent.com/5912400/209008004-f7631a2b-2ecd-46d9-b4d0-121044895eac.png)

players view
![secret_rolls_player](https://user-images.githubusercontent.com/5912400/209007994-d4dc9671-ae86-4722-84fb-139ae566000f.png)

im inclined to leave it as is with the secret rolls enabled and the GM can reveal them whenever they want to. In reality it doesnt make that much of a difference when looking at the turn tracker (except for hidden tokens). And adding more buttons to things that should be automated feels like taking a step backwards.

**Comment by ThingsCouldGetDicey** [comment]
fair enough just wanted to make sure all bases are covered. you have done a fantastic job.

**Comment by veevelder** [comment]
the module has been updated, let me know if you find an issues with it
