### ISSUE TITLE
[ISSUE] Previous playlist does not resume playing after combat

### ISSUE THREAD

**Issue by rikmarais** [veevelder/quick-combat#22]
**Describe the bug**
Previous playlist does not resume playing after combat ends if `Fanfare` playlist is set to `None`. If `Fanfare` is set to an existing playlist with a track in it, then the previous playlist does resume playing.

**To Reproduce**
1. Configure `Combat Playlist`, and `None` for `Fanfare Playlist`
2. Make sure a playlist is playing.
3. Begin combat
4. End combat
5. Does not return to the playlist that was playing in step 2.

If `Fanfare Playlist` is configured in step 1, then step 5 *does* return to the previous playlist. 

**Expected behavior**
Should return to playlist in step 2 regardless of whether a Fanfare is set.

**Screenshots**
![image](https://user-images.githubusercontent.com/34374883/204318435-e11b2ec5-70f8-49d5-a53b-149126d70d66.png)
![image](https://user-images.githubusercontent.com/34374883/204318602-0ca69dac-777b-40c8-8c22-9981b1516066.png)
^ Does not return to previous playlist, and no `Fanfare` plays

![image](https://user-images.githubusercontent.com/34374883/204318631-05527b0c-15ef-4dfe-be6b-c7239df0ecbd.png)
^ Does return to previous playlist after `Fanfare` plays

**Version Information**
 - Quick Combat: `0.3.7`
 - FoundryVTT: `10.290`
 - System: `Windows 11`
 - Other Modules: None

**Additional context**
```
Foundry Virtual Tabletop: Version 10, 10.290
Game System: dnd5e, 2.0.3
Active Modules: 1
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) FoundryVirtualTabletop/10.290.0 Chrome/104.0.5112.102 Electron/20.1.0 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 6000 x 4600 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 1

Actors: 1 | Items: 0 | Journal: 0 | Rollable Tables: 0 |
Playlists: 5 | Compendium Packs: 14 | Chat Messages: 5
```

**Comment by ThingsCouldGetDicey** [comment]
to add to this i believe the conflict is caused when a audio needed by a scene i.e if its initial playlist or ambient audio/ has macro links to audio. it will not revert back to the previous playlist whilst using the forge. but when using a client it is fine.

**Comment by veevelder** [comment]
I can't seem to replicate your issue, can you provide screenshots/console log (hit F12 and go to the console tab), also try updating to the newest version I made some modifications on how the playlists are starting and it may fix your issue.

**Comment by ThingsCouldGetDicey** [comment]
i will test now

**Comment by ThingsCouldGetDicey** [comment]
![image](https://user-images.githubusercontent.com/62528192/205431563-30261981-7588-4b04-9cdf-a449e8f5ef6f.png)
i tested on firefox and it doesnt come back to the original playlist after the update

**Comment by ThingsCouldGetDicey** [comment]
![image](https://user-images.githubusercontent.com/62528192/205433338-49848807-919b-4990-bf89-b2900126ea3c.png)
my result on chrome.

**Comment by veevelder** [comment]
I think I figure out what was going on, looking at your logs it was attempting to start a playlist with no name/id I've added some checks to make sure that those exist and error if not. Can you check again, in addition can you add the debug messages to the logs? (if it still doesnt work)

![image](https://user-images.githubusercontent.com/5912400/205448235-99d34624-b5bf-4a90-af2c-8615bc21f1a2.png)

make sure the verbose is checked

**Comment by ThingsCouldGetDicey** [comment]
![image](https://user-images.githubusercontent.com/62528192/205448711-e5b94573-6366-4bda-bc17-53c7d25db138.png)

**Comment by ThingsCouldGetDicey** [comment]
after update still getting repeated messages and not resuming 
![image](https://user-images.githubusercontent.com/62528192/205449505-5f6e0019-2829-44dd-83d8-3af7f6936c41.png)

**Comment by ThingsCouldGetDicey** [comment]
is it possible i could show you whats happening?

**Comment by veevelder** [comment]
sure thing, sent a request on discord

**Comment by veevelder** [comment]
this issue should be fixed in the newest release, update and let me know if its working for you.
