### ISSUE TITLE
[ISSUE] Cascade of Error Messages Upon Login

### ISSUE THREAD

**Issue by justinthejaguar** [veevelder/quick-combat#23]
**Describe the bug**
During login for host and clients there is a cascade of error messages which indicate that Quick Combat has attempted to migrate playlists to the new settings.

**To Reproduce**
1. Enable Module
2. Save - Instance will restart
3. See error messages cascade down the entire screen.

**Expected behavior**
Either no error or one error message tops.

**Screenshots**
![image](https://user-images.githubusercontent.com/38022481/205502954-d07914f1-1886-4414-a8ed-cf377b7680a3.png)

**Version Information**
 - Quick Combat: 0.3.9
 - FoundryVTT: 10.291
 - System: OSE 1.6.8
 - Other Modules: Ran in test instance with no modules.

**Additional context**
This may be an issue since the latest Foundry VTT version. I have not tested in other systems.

**Comment by veevelder** [comment]
I am aware of the issue, it has something to do with The Forge, I am working on a fix.

**Comment by justinthejaguar** [comment]
> I am aware of the issue, it has something to do with The Forge, I am working on a fix.

I run mine on a raspberry pi node.js

**Comment by veevelder** [comment]
Ok, thanks for the information.

**Comment by veevelder** [comment]
I should have fixed this issue, can you update to the latest version and let me know if stopped spamming.

**Comment by justinthejaguar** [comment]
This stops the spamming.
