### ISSUE TITLE
[ISSUE] quick-combat error

### ISSUE THREAD

**Issue by justinthejaguar** [veevelder/quick-combat#24]
**Describe the bug**
I get quick-combat errors in the console. These appear to be the old playlists I used for this module that no longer exist.

**To Reproduce**
Load in module

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/38022481/206875101-7777d57e-12d6-4f24-86ca-b7af7b6bf7b3.png)

**Version Information**
 - Quick Combat: 0.4.1
 - FoundryVTT: 10.291
 - System: Old-School Essentials 1.6.8
 - Other Modules:

**Additional context**
I haven't seen any detrimental impact to the session. I just thought it was odd, and should be reported.

**Comment by veevelder** [comment]
This error is when quick-combat is attempting to migrate from the old settings to the new settings, really it just means that it couldn't find the correct playlist when migrating. The error should only happen the first time when loading into the new version and will require the GM to fix it. Do you notice the error happening multiple times when loading the game?

**Comment by justinthejaguar** [comment]
It happens every login.

**Comment by veevelder** [comment]
ok, ive found the issue and fixed it. Let me know if its working for you. You will probably get one more error message but after that it should stop.

**Comment by justinthejaguar** [comment]
That fixed it. Thank you!
