### ISSUE TITLE
[FEATURE] if nothing is in playlist resume previous audio

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [veevelder/quick-combat#25]
**Is your feature request related to a problem? Please describe.**
when nothing is in the playlist it wont resume. 

**Describe the solution you'd like**
when it sees nothing is in the playlist resume to previous. 

**Describe alternatives you've considered**

**Additional context**

**Comment by veevelder** [comment]
done, in addition if the playlist is empty you will see a `{!}` symbol next to its name in the settings.
