### ISSUE TITLE
playback stopped working in new version of pf2[ISSUE]

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [veevelder/quick-combat#26]
**Describe the bug**
in the latest version of pf2 the playback and the shortcut for rolls have stopped working. there was some major refactoring in the new version of the system which i think has affected the mod.

**To Reproduce**
1. Go to have a playlist
2. Click on play
3. no sound happens. 

**Expected behavior**

**Screenshots**

**Version Information**
![image](https://user-images.githubusercontent.com/62528192/211173879-0d394af8-ec66-4d7d-ad3b-682d70c61c0c.png)

 - Quick Combat: 
 - FoundryVTT: 
 - System:
 - Other Modules:

**Additional context**

**Comment by veevelder** [comment]
so I took a look at it, and I was one PF2E version 4.6.6 and wasn't able to recreate the error, can you give me the specific error message you are seeing?

**Comment by ThingsCouldGetDicey** [comment]
yeh ive checked it recently and it does work but the playback is disjointed not sure if its anything to do with the mod.  something happened between then and the update that made it work.

**Comment by ThingsCouldGetDicey** [comment]
![image](https://user-images.githubusercontent.com/62528192/213354260-5f7d6539-5c17-4625-befa-1d36be18c7c2.png)

**Comment by veevelder** [comment]
so I made some major changes on how everything works with this mod, and "hopefully" your issues are now fixed can you give it a shot and let me know if you find anything

**Comment by ThingsCouldGetDicey** [comment]
> so I made some major changes on how everything works with this mod, and "hopefully" your issues are now fixed can you give it a shot and let me know if you find anything

thanks i really hope the intiative thing is sorted also, so it requests from players when players are selected and there was an issue of npc tokens not rolling initative either. i really look forward to the fix!

**Comment by veevelder** [comment]
is this still causing you issues?

**Comment by ThingsCouldGetDicey** [comment]
yes id love to show you as its not working fully

**Comment by veevelder** [comment]
issue was with another Mod blocking combat from starting with unrolled initiatives Monk's Little Details. Will add a note and possibly a popup warning.
