### ISSUE TITLE
Split the functionality?

### ISSUE THREAD

**Issue by Belgaron** [veevelder/quick-combat#29]
The ability to play music when combat starts seems like it could be setting independent, and it would be the COOLEST thing of all time to have. I play older systems (3.5e) that don't get much love. I'm begging you. I don't need any other bells and whistles this seems to come with. I think everyone who uses foundry would use a mod that starts playlists or prompts playlists when combat starts. In fact, I'm surprised this isn't core foundry. A truly system-independent feature.

I'm always forgetting to start combat music. I need this for my game. I'm just hopeless at coding. 

I haven't seen any other mods like this. I'm open to alternatives if they exist.

**Comment by veevelder** [comment]
at this time i'm not interested in splitting out this functionality. And the only other default feature my mod does is roll initiative for players. I can add a setting to disable/enable this which would make the mod only start, stop combat playlists. Let me know if this is something you would be interested in. The playlist start/stop stuff should also be system independent.

**Comment by veevelder** [comment]
also the only other combat playlist mod that I know of is https://github.com/death-save/maestro but it doesnt look like its been updated in a while.

**Comment by veevelder** [comment]
I've updated Quick Hits to add the [Initiative Mode](https://github.com/veevelder/quick-combat/wiki/Auto-Initiatives) feature, where you can Enable/Disable the rolling of initiatives when tokens are added to the combat tracker. If you set this to disabled it will give you what you are requesting. In addition this module should work with any system and i've tested it with 3.5e and it worked.
