### ISSUE TITLE
Suggestion: Option to roll Only NPC after starting combat

### ISSUE THREAD

**Issue by bakabachelor** [veevelder/quick-combat#3]
My players prefer to roll their own initiatives so I just add them by right clicking their tokens. This suggestion just removes an extra button click; ie select all shift + C to auto roll NPCs while adding PC tokens to the combat. 

There is a button in combat tracker by default "Roll NPCs" (mentioning it in case it helps.)

great job on this module

**Comment by veevelder** [comment]
added in new release.
