### ISSUE TITLE
[FEATURE] Scalable Combat Markers

### ISSUE THREAD

**Issue by Gabbaoma** [veevelder/quick-combat#31]
Hi, first of all: Thank you for this great module!

When using the Combat Marker feature I found, that the animations from JB2A are way too big. For me, this makes it hard to see anything else and it distracts my players. Please find an image as demonstration here:

![image](https://user-images.githubusercontent.com/97093071/227602829-74ea3c52-5c4a-4bd1-ad1a-9066ade6f650.png)

If possible, making the animation scalable would fix this issue. It could for example be a writeable field (1 as standard) or a slider.

Thank you!

**Comment by veevelder** [comment]
sure thing, I will look into adding this feature

**Comment by veevelder** [comment]
sorry it took a bit, but this feature has been added

**Comment by Gabbaoma** [comment]
Works perfectly. Thank you very much from me and my players! :-)
