### ISSUE TITLE
[ISSUE] Combat tracker won't advance

### ISSUE THREAD

**Issue by rockwallguy** [veevelder/quick-combat#32]
**Describe the bug**
When players are logged in and a combat is active, when you hit the right arrow to advance to the next actor's turn, the tracker briefly advances, then immediately reverts to the first actor in the tracker.

**To Reproduce**
1. I can only duplicate the problem while other players are logged in.  When I'm logged in alone as GM, I don't see the error.
2. Put the players in a combat with some NPCs, roll initiative, and begin combat.  For my testing, to keep the actions consistent during using Find the Culprit, I did not use quick combat to start combats.  I selected tokens, right clicked them and added them to combat via the sword and shield icon on the bottom right, then clicked "roll all" on the combat tracker to roll initiative, then hit "begin combat" at the bottom of the tracker.
3. Advance to the next person in initiative by clicking the right arrow at the bottom of the combat tracker and the tracker will briefly move to the next person before reverting to the first person on the tracker.  

**Expected behavior**
Obviously, I would expect it to advance to the next actor and stay there.

**Screenshots**
Static screenshots aren't helpful and I don't think I have video capture software installed. 

**Version Information**
 - Quick Combat: 0.4.9
 - FoundryVTT: 10.291
 - System: PF2e 4.10.3 (also tested a different world with D&D5e 2.1.5 with similar results)
 - Other Modules: Tested alone

**Additional context**

- There is no error in the console.
- The bug only happens while other players are logged in.
- It happens with only quick combat enabled and the problem goes away when I disable quick combat (with or without my usual mods)
- Intuitively to me, it doesn't feel like the culprit should be quick combat, but I tried isolating it to a different cause and couldn't replicate it with quick combat disabled.

**Comment by veevelder** [comment]
this has been fixed, just a note that there is currently an issue with the turn markers doing applying a ton of the animations for the first turn on the first round, with the next rounds being fine
