### ISSUE TITLE
Are you upgrading to v11?

### ISSUE THREAD

**Issue by YenBenGrey** [veevelder/quick-combat#34]
As the title says. Any news?

**Comment by tehguitarist** [comment]
I didn't test all functions of the module - but by changing the module.json to be v11 compatible these features at least work fine with no console errors:

- Auto rolling NPC initiative
- Starting battle music
- Playing fanfare
- Returning to original playlist

I'll hold off making a manifest PR until more testing can be done, I just had a vested interest in those features (XP etc is handled elsewhere in pf2e, and I use milestone advancement in 5e). I can run one up if needs be though, but it's only changing a couple of lines.

**Comment by veevelder** [comment]
sorry about the delay, I am planning on updating to v11 and im glad to hear most of the features just work. Ill go through and test some of the other stuff and will hopefully have it updated soon

**Comment by veevelder** [comment]
finished testing and updating for version 11, let me know if you find any other bugs.

**Comment by YenBenGrey** [comment]
Hello, 

Just tested that parts I use - 
Prompt for music or sounds when combat has started 👍 
Token Markers to show whose turn it is 👍 
Remove NPC when defeated 👍 
Music goes off when combat is over 👍 
Perfect Thank you
