### ISSUE TITLE
[FEATURE] Add the option when rolling the initiative to have Grouped initiative

### ISSUE THREAD

**Issue by davelacorneille** [veevelder/quick-combat#35]
First, thank you for this module.  I really like the macro to add combattant, start combat, next turn and ending combat.

Description of the feature:
When adding multiple NPC of the same type, have the option that they have the same initiative (like the module Group Initiative)

**Describe the solution you'd like**
Add the option when using the macro

**Describe alternatives you've considered**
Add compatibility with the module Group Initiative

**Additional context**
With Foundry 11.305, dnd5e 2.2.2, and Quick Combat 0.5.1: not compatible with Group Initiative 2.1.5

Also when adding more NPC of the same type, it should be the same initiative also.

**Comment by veevelder** [comment]
just wanted to update that I am working on this, i've just been busy lately

**Comment by veevelder** [comment]
to clarify you want to group the by the actor type and not names?

i.e. if there are 5 commoners in combat but they all have different token names you want them grouped as commoners

**Comment by davelacorneille** [comment]
Yes as actors type, as the advice in official 5e rules.

So the five commoners will have the same initiative.

**Comment by davelacorneille** [comment]
To be more specific, I don't think they should be grouped, just to have the
same initiative! :)

**Comment by veevelder** [comment]
Just another point of clarification, which option would you prefer?

1. Global Setting
  * If enabled all NPCs will be grouped together for every combat regardless of how it was started, macro, hot key, etc
2. Macro Option
  * Have 2 macros one for non-grouping npc combat and one for grouped npcs combat

**Comment by davelacorneille** [comment]
Global setting for me!

**Comment by veevelder** [comment]
feature added https://github.com/veevelder/quick-combat/wiki/Group-NPC-initiatives

let me know if its working for you

**Comment by davelacorneille** [comment]
I think that is working for the grouped initiative but I'm not able to have the auto initiative working anymore.

Do you think it is related to your last change?

**Comment by veevelder** [comment]
if you are noticing that when adding players/npcs to the combat tracker it no longer rolls initiative, thats on purpose in order to make the grouping work, initiative now rolls when starting combat. The exception is if you already have a combat started and you are adding tokens after, then their initiatives are rolled on add.

**Comment by davelacorneille** [comment]
Wow everything is perfect thank you so much :)
