### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by SixFawn253** [veevelder/quick-combat#40]
**Describe the bug**
If "Set Initiative Mode" is enabled to automatically roll missing initiatives, when it rolls, it lags a lot (a lot), even freezing the game for minutes when rolling for 15ish tokens

**To Reproduce**
1. Enable "Set Initiative Mode" to Enabled/NPC Only
2. Start an encounter with 10+ tokens
3. Do NOT roll for initiative and start the encounter

**Expected behavior**
The game will lag a lot

**Version Information**
 - Quick Combat: 0.5.6
 - FoundryVTT: 11.309
 - System: Windows 11
 - Other Modules: none

**Additional context**
Some player seems to lag too, other don't. We tested a bit and it doesn't seem to be caused by having Windows 10 or 11, neither by changing browser.

**Comment by veevelder** [comment]
I will look into it
