### ISSUE TITLE
[ISSUE] upon resume it picks up another sound not playing beforehand

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [veevelder/quick-combat#43]
**Describe the bug**
when you start the combat and play the playlist its fine, but when you end the combat and it resumes the prior music. it grabs another track and its always the same one but nothing in the settings is pointing towards it. 

**To Reproduce**
1. Go to  starting a combat. 
2. Click on any playlist setup
3. end combat

**Expected behavior**
after combat just resume previous music.

**Screenshots**

**Version Information**
 - Quick Combat: 
 - FoundryVTT: latest v11 version
 - System: pf2e
 - Other Modules: alot.

**Additional context**

**Comment by veevelder** [comment]
Added a new option to either start a new track once combat has ended or restart the last track that was playing before combat was started. See the settings [wiki](https://github.com/veevelder/quick-combat/wiki/Settings) for more details.
