### ISSUE TITLE
[FEATURE] v12 support

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [veevelder/quick-combat#45]
**Is your feature request related to a problem? Please describe.**
it would be cool if this mod gets v12 support
**Describe the solution you'd like**
no v12 compatibility errors.

**Describe alternatives you've considered**

**Additional context**

**Comment by lancir** [comment]
Is there any hope this will be updated for v12?

**Comment by veevelder** [comment]
Apologies to everyone, I have been extremely busy these past few months and expect to be so for a bit longer. However I do plan on getting the mod updated for the newest versions as well as fix the other outstanding issues. Again thank you for your patients.

**Comment by veevelder** [comment]
Added version 12 support.
