### ISSUE TITLE
Group Initiative Compatability

### ISSUE THREAD

**Issue by Lyra214** [veevelder/quick-combat#5]
I've noticed that this module rolls initiative for each token individually. Perhaps it could be modified to include support for [group initiative](https://github.com/tonifisler/foundry-group-initiative)?

**Comment by veevelder** [comment]
added in new release

**Comment by Lyra214** [comment]
Still appears to be bugged when using more than one actor of the same name.

**Comment by veevelder** [comment]
If you are talking about PCs then yes, it doesnt work, but it should work for NPCs. I will work on the PCs.

**Comment by Lyra214** [comment]
No, I'm also referring to NPCs. If I start a combat with three zombies, for example, two of them will roll initiative grouped, one will not. It also seems like that certain NPC will roll initiative twice, maybe that's the issue?

Either way, it more or less looks like [this](url
![image](https://user-images.githubusercontent.com/16280477/107286612-19abe600-6a61-11eb-8ecb-4155d209273a.png)
)

**Comment by veevelder** [comment]
ok, I think I have it fixed now, let me know if it still doesnt work.
