### ISSUE TITLE
Turn Marker Compatability

### ISSUE THREAD

**Issue by Lyra214** [veevelder/quick-combat#6]
When using Quick Combat with [Turn Marker](https://github.com/kckaiwei/TurnMarker-alt) and starting a quick combat, the combatant with the last name in alphabetical order has an additional, irremovable turn marker. This error does not happen if combat is started traditionally.

How to reproduce:

1. Install both modules.
2. Start combat between a few NPCs using CTRL+C.

**Comment by veevelder** [comment]
fixed the issue, should work now.
